#!/bin/bash

# Define the powers of 2
powers=(14 15 16 17 18)

# Define the second parameters
params=(1 2 4)

# Loop through each power of 2
for power in "${powers[@]}"; do
    n=$((2**$power))
    echo "n= 2^$power" >> par_results.txt

    # Loop through each parameter
    for param in "${params[@]}"; do
        echo "second param = $param" >> par_results.txt

        # Run the program three times with the current parameter
        for run in {1..3}; do
            echo "run$run time:" >> par_results.txt
            ./parsort $n $param >> par_results.txt
        done
        echo "" >> par_results.txt
    done

    echo "---------------------------------------" >> par_results.txt
done