#!/bin/bash

# Define the powers of 2
powers=(14 15 16 17 18)

# Loop through each power of 2
for power in "${powers[@]}"; do
    n=$((2**$power))
    echo "n= 2^$power" >> seq_results.txt

    # Run the program three times
    for run in {1..3}; do
        echo "run$run time:" >> seq_results.txt
        ./seqsort $n 0 >> seq_results.txt
    done

    echo "---------------------------------------" >> seq_results.txt
done